spring:
  messages:
    basename: message
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ms?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123
    druid:
      initial-size: 50
      min-idle: 50
      max-active: 1000
      max-wait: 60000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true

#spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/ms?useUnicode=true&characterEncoding=utf-8
#    username: root
#    password: 123
#    driver-class-name: com.mysql.jdbc.Driver
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    open-in-view: true
#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#  devtools:
#    remote:
#      secret: 1234
#      debug:
#        enabled: true
#        local-port: 8007
#    livereload:
#      enabled: true
#    restart:
#      enabled: true
#      exclude: static/**
