tests: 123

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
    #healthcheck:
      #enabled: true
  instance:
    hostname: localhost
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 9

server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 800
    accept-count: 800
