eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
    #healthcheck:
      #enabled: true
  instance:
    hostname: localhost
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 9

SMS_APIKEY: 123
SMS_TPLID: 123
eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        serviceUrl:
            defaultZone: http://tanmashan:ds686yf@127.0.0.1:8761/eureka/
    instance:
        hostname: 127.0.0.1
feign:
    hystrix:
        enabled: true
imagePath1: D:/images/cards/
imagePath2: D:/image1
imagePath3: D:/image2/
imagePath4: D:/image3/
logging:
    level:
        sample:
            mybatis:
                mapper: TRACE
mybatis:
    config-location: classpath:mybatis-config.xml
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: YOKU@3220@js
        url: jdbc:mysql://172.18.53.144:45151/xksjDB?useUnicode=true&characterEncoding=utf-8
        username: xksj
    devtools:
        livereload:
            enabled: true
        remote:
            debug:
                enabled: true
                local-port: 8007
            secret: 1234
        restart:
            enabled: true
            exclude: static/**
    freemarker:
        cache: false
        charset: UTF-8
        check-template-location: true
        content-type: text/html
        enabled: true
        suffix: .html
        template-loader-path: classpath:/templates/
    jpa:
        properties:
            hibernate:
                show_sql: true
    profiles:
        active: dev
    redis:
        database: 0
        host: 127.0.0.1
        password: kfrd159159
        pool:
            max-active: 8
            max-idle: 8
            max-wait: -1
            min-idle: 0
        port: 6379
        timeout: 0
    session:
        store-type: redis
    zipkin:
        base-url: http://localhost:9411
xk:
    default:
        filePath: /home/xk/file/
