eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
    #healthcheck:
      #enabled: true
  instance:
    hostname: localhost
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 9

security:
  basic:
    enabled: true
  user:
    name: tanmashan
    password: ds686yf
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 123
    url: jdbc:mysql://127.0.0.1:3306/ms?useUnicode=true&characterEncoding=utf-8
    username: root
  devtools:
    livereload:
      enabled: true
    remote:
      debug:
        enabled: true
        local-port: 8007
      secret: 1234
    restart:
      enabled: true
      exclude: static/**
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: true
    properties:
      hibernate:
        show_sql: true
  profiles:
    active: dev
  redis:
    database: 0
    host: 192.168.1.113
    password: UnionExpress.Service.Mysql.2016
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
      min-idle: 0
    port: 6379
    timeout: 0
